- import_role:
    name: 'debops.debops.secret'

- name: Install required packages
  package:
    name: '{{ q("flattened", (photoprism__base_packages
                              + photoprism__packages)) }}'
    state: 'present'
  register: photoprism__register_packages
  until: photoprism__register_packages is succeeded

- name: Create Photoprism system group
  group:
    name: '{{ photoprism__group }}'
    gid: '{{ photoprism__gid | default(omit) }}'
    state: 'present'
    system: True

- name: Create Photoprism system user
  user:
    name: '{{ photoprism__user }}'
    group: '{{ photoprism__group }}'
    home: '{{ photoprism__home }}'
    shell: '{{ photoprism__shell }}'
    comment: '{{ photoprism__comment }}'
    uid: '{{ photoprism__uid | default(omit) }}'
    state: 'present'
    system: True

- name: Create photoprism install directory
  file:
    path: "{{ photoprism__install_dir }}"
    state: directory
    owner: "{{ photoprism__user }}"
    group: "{{ photoprism__group }}"
    recurse: true

- name: Determine AVX extensions
  command: grep -o -m1 'avx[^ ]*' /proc/cpuinfo
  register: cpuinfo

- name: List supported AVX extensions
  set_fact:
    avx: "{{ cpuinfo.stdout | split('\n') | list }}"

- name: Determine tensorflow url
  set_fact:
    tensorflow_url: |
      {% if 'avx2' in avx %}
      https://dl.photoprism.org/tensorflow/linux/libtensorflow-linux-avx2-{{ photoprism__tensorflow_version }}.tar.gz
      {% elif 'avx' in avx %}
      https://dl.photoprism.org/tensorflow/linux/libtensorflow-linux-avx-{{ photoprism__tensorflow_version }}.tar.gz
      {% else %}
      https://dl.photoprism.org/tensorflow/linux/libtensorflow-linux-cpu-{{ photoprism__tensorflow_version }}.tar.gz
      {% endif %}

- name: Download tensorflow archive
  get_url:
    url: "{{ tensorflow_url }}"
    dest: "/tmp/libtensorflow-{{ photoprism__tensorflow_version }}.tar.gz"
  register: tf_download

- name: Extract tensorflow archive
  unarchive:
    src: "{{ tf_download.dest }}"
    remote_src: yes
    # TODO: Ideally we would unpack this into /opt/tensorflow but still have the
    # go compilation find it.
    dest: /usr/local
  register: install_tensorflow

- name: Run ldconfig
  command: ldconfig
  when: install_tensorflow.changed

- name: Make src dir
  file:
    state: directory
    path: "{{ photoprism__golang_src }}"
    owner: "{{ photoprism__user }}"

- name: Run debops golang role
  import_role:
    name: debops.debops.golang
  vars:
    golang__dependent_packages:
      - '{{ photoprism__golang_dependent_packages }}'
    golang__gosrc: '{{ photoprism__golang_src }}'
    golang__user: '{{ photoprism__user }}'
    golang__group: '{{ photoprism__group }}'
    golang__home: '{{ photoprism__home }}'
    golang__shell: '{{ photoprism__shell }}'
    golang__comment: '{{ photoprism__comment }}'

- name: Copy the photoprism assets folder
  ansible.builtin.copy:
    src: "{{ photoprism__golang_src }}/github.com/photoprism/photoprism/assets/"
    dest: "{{ photoprism__assets_dir }}"
    remote_src: yes

- name: Copy the photoprism assets folder
  ansible.builtin.copy:
    src: "{{ photoprism__golang_src }}/github.com/photoprism/photoprism/scripts/dist/heif-convert.sh"
    dest: "/opt/photoprism/heif-convert"
    remote_src: yes

- name: Template the photoprism environment file
  template:
    src: photoprism.env.j2
    dest: "{{ photoprism__home }}/.env"
    owner: "{{ photoprism__user }}"
  notify:
    - Restart Photoprism

- name: Template the photoprism service file
  template:
    src: photoprism.service.j2
    dest: "/etc/systemd/system/photoprism.service"
  notify:
    - Restart Photoprism
