---
# Copyright (C) 2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# A separate handler is needed to ensure the correct order of execution
- name: Reload systemd daemon (babybuddy)
  systemd:
    daemon_reload: True
  when: ansible_service_mgr == 'systemd'

- name: Restart gunicorn for babybuddy
  service:
    name: 'gunicorn@babybuddy'
    state: 'restarted'
  when: (not babybuddy__app_internal_appserver|bool and
         ansible_local.gunicorn.installed|d()|bool)

- name: Restart babybuddy internal appserver
  service:
    name: 'babybuddy'
    state: 'restarted'
    enabled: True
  when: babybuddy__app_internal_appserver|bool
