mobilizon__fqdn:
mobilizon__email_from:
mobilizon__email_reply_to: "{{ mobilizon__email_from }}"
mobilizon__name:
mobilizon__description:
mobilizon__open_registrations: false
mobilizon__demo: false
mobilizon__allow_relay: true
mobilizon__federating: true

mobilizon__app: "/opt/mobilizon/"

# List of APT packages which are required by the Mobilizion application.
mobilizon__base_packages:
  - curl
  - tar
  - nginx
  - certbot
  - imagemagick
  - file
  - postgis
  - gifsicle
  - jpegoptim
  - optipng
  - pngquant

mobilizon__packages: []

# Name of the UNIX system account used to manage Mobilizion.
mobilizon__user: 'mobilizon'

# Name of the UNIX primary group used to manage Mobilizion.
mobilizon__group: 'mobilizon'

# The default shell set on the Mobilizion account.
mobilizon__shell: '/usr/sbin/nologin'

mobilizon__home: '{{ (ansible_local.fhs.home | d("/var/local"))
                  + "/" + mobilizon__user }}'

# Directory where the Mobilizion application directory is located.
mobilizon__lib: '{{ (ansible_local.fhs.lib | d("/usr/local/lib"))
                 + "/" + mobilizon__user }}'

mobilizon__etc:  '/etc/{{ mobilizon__user }}'

mobilizon__database_host: '{{ ansible_local.postgresql.server|d("localhost") }}'

# The TCP port of the PostgreSQL database server which should be used by Netbox.
mobilizon__database_port: '{{ ansible_local.postgresql.port|d("5432") }}'

# Name of the PostgreSQL database and its corresponding role used by Mobilizion.
# This role won't be able to login to the database server directly.
mobilizon__database_name: 'mobilizon_production'

# Name of the PostgreSQL role used by Mobilizion. This role will be able to login
# to the PostgreSQL server and access the Mobilizion database.
mobilizon__database_user: '{{ mobilizon__user }}'

# Autogenerated password to the Mobilizion PostgreSQL user role.
mobilizon__database_password: '{{ lookup("password", secret + "/postgresql/" +
                               (ansible_local.postgresql.delegate_to|d("localhost")) + "/" +
                               (ansible_local.postgresql.port|d("5432")) + "/credentials/" +
                               mobilizon__database_user + "/password") }}'

mobilizon__database_ssl: true

mobilizon__local_http_port: 4000
mobilizon__app_timeout: 5

# Role configuration for the :ref:`debops.postgresql` Ansible role.
mobilizon__postgresql__dependent_roles:
  - name: '{{ mobilizon__database_user }}'
  - name: '{{ mobilizon__database_name }}'
    flags: [ 'NOLOGIN' ]

# Group configuration for the :ref:`debops.postgresql` Ansible role.
mobilizon__postgresql__dependent_groups:
  - roles: [ '{{ mobilizon__database_user }}' ]
    groups: [ '{{ mobilizon__database_name }}' ]
    database: '{{ mobilizon__database_name }}'

# Database configuration for the :ref:`debops.postgresql` Ansible role.
mobilizon__postgresql__dependent_databases:
  - name: '{{ mobilizon__database_name }}'
    owner: '{{ mobilizon__database_name }}'

# Database configuration for the :ref:`debops.postgresql` Ansible role.
mobilizon__postgresql__dependent_extensions:
  - database: '{{ mobilizon__database_name }}'
    extension: 'pg_trgm'
  - database: '{{ mobilizon__database_name }}'
    extension: 'postgis'
  - database: '{{ mobilizon__database_name }}'
    extension: 'unaccent'

# Upstream configuration for the :ref:`debops.nginx` Ansible role.
mobilizon__nginx__dependent_upstreams:
  - name: 'mobilizon'
    server: 'localhost:{{ mobilizon__local_http_port }}'

# Server configuration for the :ref:`debops.nginx` Ansible role.
mobilizon__nginx__dependent_servers:
  - name: '{{ mobilizon__fqdn }}'
    by_role: 'debops.mobilizon'
    filename: 'debops.mobilizon'
    location:
      '/': |
        proxy_pass http://mobilizon;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout {{ mobilizon__app_timeout }};
        proxy_send_timeout {{ mobilizon__app_timeout }};
        proxy_read_timeout {{ mobilizon__app_timeout }};
