- name: Photoprism
  hosts: [ 'cadair_service_photoprism_test' ]
  become: True

  collections:
    - debops.debops
    - cadair.debops

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: resolvconf
      tags: [ 'role::resolvconf', 'skip::resolvconf' ]
      resolvconf__enabled: True

    # - role: ferm
    #   tags: [ 'role::ferm', 'skip::ferm' ]
    #   ferm__dependent_rules:
    #     - '{{ nginx__ferm__dependent_rules }}'

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::nodejs' ]
      keyring__dependent_apt_keys:
        - '{{ nodejs__keyring__dependent_apt_keys }}'
        - '{{ golang__keyring__dependent_gpg_keys }}'

    - role: apt_preferences
      tags: [ 'role::apt_preferences', 'skip::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ photoprism__apt_preferences_dependent_list | d([]) }}'
        # - '{{ nginx__apt_preferences__dependent_list | d([]) }}'
        - '{{ nodejs__apt_preferences__dependent_list | d([]) }}'
        - '{{ golang__apt_preferences__dependent_list | d([]) }}'

    - role: mariadb
      tags: [ 'role::mariadb', 'skip::mariadb' ]
      mariadb__dependent_users:
        - '{{ photoprism__mariadb__dependent_users }}'
      mariadb__dependent_databases:
        - '{{ photoprism__mariadb__dependent_databases }}'

    - role: nodejs
      tags: [ 'role::nodejs', 'skip::nodejs' ]
      nodejs__node_upstream: false
      nodejs__node_upstream_release: "node_12.x"
      nodejs__yarn_upstream: true

    # - role: nginx
    #   tags: [ 'role::nginx', 'skip::nginx' ]
    #   nginx__dependent_servers:
    #     - '{{ photoprism__nginx__dependent_servers }}'

    - role: photoprism
      tags: [ 'role::photoprism', 'skip::photoprism' ]
