- name: Valheim
  hosts: [ 'cadair_service_valheim' ]
  become: True

  collections:
    - debops.debops
    - cadair.debops

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: resolvconf
      tags: [ 'role::resolvconf', 'skip::resolvconf' ]
      resolvconf__enabled: True

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::docker_server' ]
      keyring__dependent_apt_keys:
        - '{{ docker_server__keyring__dependent_apt_keys }}'

    - role: etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ docker_server__etc_services__dependent_list }}'

    - role: python
      tags: [ 'role::python', 'skip::python', 'role::docker_server' ]
      python__dependent_packages3:
        - '{{ docker_server__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ docker_server__python__dependent_packages2 }}'

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ docker_server__ferm__dependent_rules }}'
        - '{{ valheim_server__ferm__dependent_rules }}'

    - role: docker_server
      tags: [ 'role::docker_server', 'skip::docker_server' ]

    - role: valheim
      tags: [ 'role::valheim', 'skip::valheim' ]
